version: '3.7'

services:
  python:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    labels:
      - "traefik.backend=${podName}-python"
      - "traefik.frontend.rule=Host:${hostRule}"
      - "traefik.docker.network=${podName}_frontend"
      - "traefik.port=80"

    networks:
      - frontend
    volumes:
      - ./msmtp/msmtprc:/etc/msmtprc

networks:
  frontend:
