version: '3.7'

services:
  python:
    build: .
    image: ${podName}/python
    restart: unless-stopped
    ports:
    - 8000:8000
    networks:
      - frontend
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
